import { ProjectContext, InstructionTarget, SECTION_ORDER, CATEGORY_ORDER } from './types';
import { CONFIG_VARIABLES, FILE_TYPES } from './data';

const BANNER = '<!-- Generated by Triforge — do not edit; regenerated from the Triton knowledge base. -->';

/** Canonical on-disk path of the generated Triton knowledge base, relative to the project root.
 *  Single source of truth — imported by the VS Code adapters so the path contract stays DRY. */
export const KB_REL = 'docs/triton-knowledge.md';

function configVarLine(v: (typeof CONFIG_VARIABLES)[number]): string {
  const meta = [v.valueType, v.unit ? `${v.unit}` : '', v.allowed ? `one of ${v.allowed.join('|')}` : '']
    .filter(Boolean).join(', ');
  const def = v.defaultValue === '' ? 'empty' : `\`${v.defaultValue}\``;
  const ui = v.uiValue !== undefined ? `; reference UI default \`${v.uiValue}\`` : '';
  const note = v.note ? ` _(${v.note})_` : '';
  return `- **${v.name}** (${meta}; default ${def}${ui}) — ${v.details}${note}`;
}

/** The full Triton knowledge-base document body. Static + deterministic. */
export function renderKnowledgeBaseMarkdown(): string {
  const out: string[] = [];
  out.push(BANNER, '');
  out.push('# Triton Knowledge Base', '');
  out.push('Triton is a flood-inundation simulator. A Triton project is driven by a flat',
    '`triton_execution.cfg` run configuration plus a set of raster and tabular input files.',
    'This document is the canonical reference for its file types and configuration variables.', '');

  out.push('## File types', '');
  for (const cat of CATEGORY_ORDER) {
    const items = FILE_TYPES.filter((f) => f.category === cat).sort((a, b) => a.id.localeCompare(b.id));
    if (!items.length) continue;
    out.push(`### ${cat}`, '');
    for (const f of items) {
      const exts = f.extensions.length ? ` (${f.extensions.join(', ')})` : '';
      const vars = f.relatedVars.length ? ` Related config: ${f.relatedVars.join(', ')}.` : '';
      const note = f.note ? ` _(${f.note})_` : '';
      out.push(`- **${f.label}**${exts} — ${f.role} ${f.format}${vars}${note}`);
    }
    out.push('');
  }

  out.push('## Configuration variables', '');
  for (const section of SECTION_ORDER) {
    const items = CONFIG_VARIABLES.filter((v) => v.section === section).sort((a, b) => a.name.localeCompare(b.name));
    out.push(`### ${section}`, '');
    for (const v of items) out.push(configVarLine(v));
    out.push('');
  }

  out.push('## Execution model', '');
  out.push('Two orthogonal axes. `executable_target_mode` = source | executable | docker',
    '(where the binary comes from). `execution_type` = interactive | batch (how it runs;',
    'batch generates a submit script for a scheduler such as sbatch). MPI/HPC invocation is',
    'free-text (e.g. `mpirun -n <cpus-1> <exe>`). Computation parameters such as `courant`,',
    '`time_step`, `domain_decomposition`, and `gpu_direct_flag` are cfg values, not CLI flags.', '');

  return out.join('\n');
}

/** The compact, manifest-derived project-context block (managed region body). */
export function renderProjectContextBlock(ctx: ProjectContext): string {
  const out: string[] = [];
  out.push('## Triton project context', '');
  out.push(`- **Project:** ${ctx.name}`);
  if (ctx.description) out.push(`- **Description:** ${ctx.description}`);
  out.push(`- **CRS:** ${ctx.crs || '(unset)'}`);
  if (ctx.derivedCrs && ctx.derivedCrs !== ctx.crs) {
    out.push(`- **Derived CRS:** ${ctx.derivedCrs} (from UTM ${ctx.utmZone} / ${ctx.datum})`);
  }
  out.push(`- **UTM zone / datum:** ${ctx.utmZone || '(unset)'} / ${ctx.datum || '(unset)'}`);
  out.push(`- **Formats:** input ${ctx.inputFormat} → output ${ctx.outputFormat}`);
  out.push(`- **Directories:** input \`${ctx.inputDir}\`, output \`${ctx.outputDir}\`, build \`${ctx.buildDir}\``);
  if (ctx.hasImportedLegacy) {
    out.push('- **Note:** this project was imported from a legacy Triton config; some settings are preserved unparsed.');
  }
  return out.join('\n');
}

const ORIENTATION =
  `This is a **Triton** flood-inundation simulation project (managed by the Triforge extension). ` +
  `For the canonical reference on Triton file types and configuration variables, see ` +
  `[\`${KB_REL}\`](${KB_REL}).`;

/** The managed-block body for each marker-spliced instruction target. */
export function renderTarget(target: InstructionTarget, ctx: ProjectContext): string {
  switch (target) {
    case 'claude':
      // Thin shim: Claude reads CLAUDE.md and imports AGENTS.md (which carries the context).
      return '@AGENTS.md';
    case 'copilot':
      // Copilot ignores @imports → plain-text pointer.
      return `${renderProjectContextBlock(ctx)}\n\n` +
        `See \`${KB_REL}\` for the Triton knowledge base (file types and configuration variables).`;
    case 'agents':
    case 'gemini':
    case 'cursor':
    default:
      return `${renderProjectContextBlock(ctx)}\n\n${ORIENTATION}`;
  }
}
