import { describe, it, expect } from 'vitest';
import { renderKnowledgeBaseMarkdown, renderProjectContextBlock, renderTarget } from './render';
import { CONFIG_VARIABLES, FILE_TYPES } from './data';
import { SECTION_ORDER, CATEGORY_ORDER, ProjectContext } from './types';

const ctx: ProjectContext = {
  name: 'Demo', description: 'A demo study', crs: 'EPSG:32616', derivedCrs: 'EPSG:32616',
  utmZone: '16N', datum: 'WGS84', inputFormat: 'BIN', outputFormat: 'ASC',
  inputDir: 'input', outputDir: 'output', buildDir: 'build', hasImportedLegacy: false,
};

describe('renderKnowledgeBaseMarkdown', () => {
  it('is deterministic (byte-identical across calls)', () => {
    expect(renderKnowledgeBaseMarkdown()).toBe(renderKnowledgeBaseMarkdown());
  });
  it('contains every config-variable name and every section heading in canonical order', () => {
    const md = renderKnowledgeBaseMarkdown();
    for (const v of CONFIG_VARIABLES) expect(md).toContain(v.name);
    const idxs = SECTION_ORDER.map((s) => md.indexOf(`### ${s}`));
    expect(idxs.every((i) => i >= 0)).toBe(true);
    expect([...idxs]).toEqual([...idxs].sort((a, b) => a - b)); // sections in canonical order
    const cidx = CATEGORY_ORDER.map((c) => md.indexOf(`### ${c}`));
    expect(cidx.every((i) => i >= 0)).toBe(true);
    expect([...cidx]).toEqual([...cidx].sort((a, b) => a - b)); // categories in canonical order
    for (const f of FILE_TYPES) expect(md).toContain(f.label);
  });
  it('carries the generated banner', () => {
    expect(renderKnowledgeBaseMarkdown()).toContain('Generated by Triforge');
  });
  it('surfaces the reference-UI default for template-vs-UI conflicts', () => {
    const md = renderKnowledgeBaseMarkdown();
    expect(md).toContain('reference UI default');
    expect(md).toContain('`0.01`'); // time_step's reference-UI value
  });
});

describe('renderProjectContextBlock', () => {
  it('reflects the context and contains no timestamps', () => {
    const out = renderProjectContextBlock(ctx);
    expect(out).toContain('Demo');
    expect(out).toContain('EPSG:32616');
    expect(out).toContain('BIN');
    expect(out).not.toMatch(/\d{4}-\d{2}-\d{2}T/); // no ISO timestamps
  });
  it('shows a derived-CRS line only when derivedCrs differs from or fills an empty crs', () => {
    expect(renderProjectContextBlock({ ...ctx, crs: '', derivedCrs: 'EPSG:32616' })).toMatch(/derived/i);
    expect(renderProjectContextBlock({ ...ctx, crs: 'EPSG:9999', derivedCrs: 'EPSG:32616' })).toMatch(/derived/i);
    expect(renderProjectContextBlock({ ...ctx, crs: 'EPSG:32616', derivedCrs: 'EPSG:32616' })).not.toMatch(/derived/i);
    expect(renderProjectContextBlock({ ...ctx, crs: 'EPSG:9999', derivedCrs: undefined })).not.toMatch(/derived/i);
  });
  it('notes imported legacy data when present', () => {
    expect(renderProjectContextBlock({ ...ctx, hasImportedLegacy: true })).toMatch(/legacy/i);
  });
});

describe('renderTarget', () => {
  it('claude is the @AGENTS.md shim', () => {
    expect(renderTarget('claude', ctx)).toContain('@AGENTS.md');
  });
  it('agents/gemini reference the knowledge base', () => {
    expect(renderTarget('agents', ctx)).toContain('docs/triton-knowledge.md');
    expect(renderTarget('gemini', ctx)).toContain('docs/triton-knowledge.md');
  });
  it('copilot uses a plain-text pointer (no @import)', () => {
    const out = renderTarget('copilot', ctx);
    expect(out).toContain('docs/triton-knowledge.md');
    expect(out).not.toContain('@docs');
  });
});
